export const ALL_HERO_FAIL = "ALL_HERO_FAIL";

export const ALL_HERO_REQUEST = "ALL_HERO_REQUEST";
export const ALL_HERO_SUCCESS = "ALL_HERO_SUCCESS";

export const ADMIN_HERO_REQUEST = "ADMIN_HERO_REQUEST";
export const ADMIN_HERO_SUCCESS = "ADMIN_HERO_SUCCESS";
export const ADMIN_HERO_FAIL = "ADMIN_HERO_FAIL";


export const UPDATE_HERO_REQUEST = "UPDATE_HERO_REQUEST";
export const UPDATE_HERO_SUCCESS = "UPDATE_HERO_SUCCESS";
export const UPDATE_HERO_FAIL = "UPDATE_HERO_FAIL";
export const UPDATE_HERO_RESET = "UPDATE_HERO_RESET";

export const HERO_DETAILS_REQUEST = "HERO_DETAILS_REQUEST";
export const HERO_DETAILS_FAIL = "HERO_DETAILS_FAIL";
export const HERO_DETAILS_SUCCESS = "HERO_DETAILS_SUCCESS";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
